[project]
name = "libemg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bleak>=3.0.2",
    "datetime>=6.0",
    "dearpygui>=2.3.1",
    "h5py>=3.16.0",
    "librosa>=0.11.0",
    "linkify-it-py==2.0.0",
    "matplotlib>=3.11.0",
    "myst-parser>=4.0.0",
    "onedrivedownloader>=1.1.3",
    "opencv-python>=4.13.0.92",
    "pillow>=12.2.0",
    "pyomyo==0.0.5",
    "pyserial>=3.5",
    "pytest==7.1.3",
    "pytest-cov==4.0.0",
    "pytest-skip-slow==0.0.3",
    "pywavelets>=1.9.0",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
    "sifi-bridge-py==2.0.0b19",
    "sphinx>=8.1.3",
    "sphinx-rtd-theme>=3.0.2",
    "websockets==8.1",
    "wfdb>=4.3.1",
]
