name: Workflow for Codecov example-python
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pytest
        run: pytest --cov emg_feature_extraction
      # - name: Run tests and collect coverage
      #   run: pytest --cov emg_feature_extraction
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      # - name: Check for under 100% coverage
      #   run: coverage report --fail-under=100