name: Workflow for Codecov example-python
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pytest
<<<<<<< HEAD
        run: python -m pytest
=======
        run: pytest
>>>>>>> e2dc15d8212b4936679fff970bbf6bc44b2c96bf
      # - name: Run tests and collect coverage
      #   run: pytest --cov emg_feature_extraction
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      # - name: Check for under 100% coverage
      #   run: coverage report --fail-under=100